### ISSUE TITLE
pyproject.toml: pyminifier as build-backend

### ISSUE THREAD

**Issue by nschloe** [liftoff/pyminifier#133]
Modern Python projects define their build requirements in `pyproject.toml`, e.g.,
```toml
[build-system]
requires = [
  "setuptools>=42",
  "wheel",
]
build-backend = "setuptools.build_meta"
```
It'd be nice addition of pyminifier could be defined as the builder, e.g.,
```toml
[build-system]
requires = [
  "setuptools>=42",
  "wheel",
  "pyminifier>=xyz",
]
build-backend = "pyminifier.build_meta"
```
to spit out a minified package code.
